### ISSUE TITLE
Dagger2 for injection, dinject for route generation

### ISSUE THREAD

**Issue by richarddd** [dinject/dinject#21]
Hi,

Love this library! But there are some dagger features that I miss such as multi-bindings etc.

Wouldn't it be an idea to leverage dagger for injection of dependencies and use dinject for code generation of routes? That way we get all the features of dagger2, your library becomes way less complex and could focus more on route/API generation than competing with dagger for DI?

Just a thought :)

**Comment by rbygrave** [comment]
> leverage dagger for injection of dependencies 

By all means put up a proof of concept for that.  The fundamental thing we need the DI to do is provide the list of WebRoute to register.

```java
    List<WebRoutes> webRoutes = SystemContext.getBeans(WebRoutes.class);

    app.routes(() -> webRoutes.forEach(WebRoutes::registerRoutes));
```
... I did have a good look at Dagger2 and Micronaut prior to this effort and created DInject because I was not satisfied with either.  There are a few other interesting APT DI libraries as well (for Andriod).


> multi-bindings

Depends on specifics a bit but with DInject (like Spring DI) we just depend on a List of <dependency> and they are injected. 

https://github.com/dinject/dinject/blob/master/src/test/java/org/example/coffee/list/CombinedSomei.java#L14


> your library becomes way less complex 

Well, I built DInject because Dagger2 has historically had a Andriod focus and lacked the features/focus we need for server-side development.  For example, Lifecycle support.

The good news as I see it (as a maintainer) is that the DI feature set is pretty well known (from my server side Spring/Guice perspective at least). In theory we are pretty stable implementation wise already.


> could focus more on route/API generation

Technically the relationship between the controller code generation and DI generation is ... that the controller code generates classes with `@Singleton` - that's it.  So any DI library that understands `@Singleton` can be used right now with no change (just don't bring in the DInject annotation processor). 

If Dagger2 (or anything else) is better then that ought to work.

**Comment by richarddd** [comment]
Alright cool, thanks for the update!

I guess I could try just code generation and discover the routes with Dagger 😀

Saw that you have provided support for multibindings for lists. Do you have support for sets and maps as well? Dagger has the awesome `@ElementsIntoSet` and `@IntoMap` etc

**Comment by rbygrave** [comment]
*>  Do you have support for sets and maps as well? Dagger has the
awesome @ElementsIntoSet and @IntoMap etc*

No.

In theory we could write some code to turn List<Foo> into Set<foo> or
Map<?,Foo> ... and the question would be do we really want DInject to do
that.  If someone (yourself) wanted to push support for that it would be
good to hear the practical use case.  Sets imply hashCode/equals which I
have never implemented on a `@Singleton` component (so the use/need of Set
seems strange to me).


Cheers, Rob.

**Comment by rbygrave** [comment]
*> discover the routes with Dagger*

Absolutely - I'm keen to see it so definitely let me know how you go.

Cheers, Rob.

**Comment by rbygrave** [comment]
Ok, I'll close this for now.  Re-open or update etc when you have a dagger2 example.

Thanks, Rob.
